### ISSUE TITLE
question: isn't UsePrivilegeSeparation deprecated?

### ISSUE THREAD

**Issue by fintzd** [ovh/debian-cis#106]
Hello everyone! 

I'm not sure if this is just me, so I didn't want to start a fork and edits for it until it is not confirmed.

In script [99.5.2.8](https://github.com/ovh/debian-cis/blob/334d743125166853d04a389679c24222fe8d6874/bin/hardening/99.5.2.8_ssh_sys_sandbox.sh), seems to me to be a deprecated option. 

Is there a reason for keeping this on? 

Thanks!

**Comment by thibaultserti** [comment]
Yes it's totally deprecated. We kept it here for backward compatibility but in fact it's a bit useless.
We will probably clean old deprecated checks when CIS guide for Debian 11 will launch.
The best here is to disable this check.

**Comment by fintzd** [comment]
Thank you @thibaultserti ! Got it! :)
