### ISSUE TITLE
SSH protocol 2 check is obsolete

### ISSUE THREAD

**Issue by melak** [ovh/debian-cis#113]
https://github.com/ovh/debian-cis/blob/faf5b155e51e89ba4325844d796e1ca54b4d0d93/bin/hardening/5.2.4_sshd_protocol.sh#L1

Protocol 1 support was removed from OpenSSH 7.4. Debian 8 might conceivably have been the last one shipping with OpenSSH earlier than that (as Stretch was shipped with 7.4). Debian 8 has reached end of life and [end of security support](https://www.debian.org/News/2020/20200709) more than a year ago. This check results in a false positive in pretty much all supported configurations (except possibly those that have been upgrades from older Debian versions and have not had their configuration properly updated).

Sounds like a good time to retire this check entirely, I suppose.

**Comment by thibaultserti** [comment]
Hello I checked and you're right ! The reason that it's still there is that it is still in the debian 10 CIS guide.
There is other scripts as well that are fairly deprecated and I think we will remove them in the next big release (when Debian 11 guide will come out)

**Comment by melak** [comment]
I've raised a couple of tickets against some of the affected benchmarks.

**Comment by thibaultserti** [comment]
Well good luck, I've heard that they are not the quickest people to answer ...

**Comment by melak** [comment]
On the bright side though you still have a cozy handful of years to carefully deliberate that `git rm` 😁

**Comment by ThibaultDewailly** [comment]
Not impacting the normal behaviour of the script, this will be removed from the repository when the last supported Debian with this recommendation will disappear.
