### ISSUE TITLE
Newline issue when appending SSH config to /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by noqcks** [ovh/debian-cis#13]
I run apply to automatically update SSH rules, but `/etc/ssh/sshd_config` doesn't seem to end with a newline by default! classic!

`9.3.5_sshd_maxauthtries.sh` uses the default `add_end_of_file` which results in two parameters being located on the same line like so: 
```
UseDNS noMaxAuthTries 4
```

which causes ssh service to fail a restart 
```
 /etc/ssh/sshd_config line 89: Bad yes/no argument: noMaxAuthTries
```

```
root@ip-172-31-47-112:/tmp/debian-cis# ssh -V
OpenSSH_6.7p1 Debian-5+deb8u4, OpenSSL 1.0.1t  3 May 2016
root@ip-172-31-47-112:/tmp/debian-cis# uname -a
Linux ip-172-31-47-112 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
```

**Comment by thibaultserti** [comment]
Hello,
the project was not maintained since 2018 but there is now people to support it.
It has been updated to debian 10. Be free to use it and report bugs if you find any !

Best regards
