### ISSUE TITLE
Debian 11

### ISSUE THREAD

**Issue by bert2002** [ovh/debian-cis#138]
Hi,
are there plans to support Debian 11 in the near future?

Thanks,
bert

**Comment by tdenof** [comment]
Just to add some clarifications to my answer, for now Debian 11 CIS benchmark hasn't been released yet by cisecurity.org (cf https://www.cisecurity.org/cis-benchmarks/), so all we can do is fixing compatibility issues on Debian 11 for the current hardening scripts based on Debian 10 benchmark

**Comment by bert2002** [comment]
Thanks @tdenof . Its just for planning if you will continue supporting it in the future.
