### ISSUE TITLE
There are have two files cannot be configured, When --set-hardening-level is executed.

### ISSUE THREAD

**Issue by Samson-W** [ovh/debian-cis#15]
There are have two files cannot be configured, When --set-hardening-level is executed.

Example: 
~# bash ./bin/hardening.sh --set-hardening-level 3
The script 99.1_timeout_tty doesn't have a hardening level, configuration untouched for it
The script 99.2_disable_usb_devices doesn't have a hardening level, configuration untouched for it

**Comment by thibaultserti** [comment]
Hello,
the project was not maintained since 2018 but there is now people to support it.
It has been updated to debian 10. Be free to use it and report bugs if you find any !

Best regards
