### ISSUE TITLE
Debian 11 support  ?

### ISSUE THREAD

**Issue by inf0rmix** [ovh/debian-cis#162]
Do you plan Debian 11 support ?

I cannot see anything about bullseye

**Comment by ThibaultDewailly** [comment]
Hello !

CIS Community just published yesterday it's first draft subjected to review.

Freeze period will begin soon, following by tickets and issues closure to release to stable.
It's only then that we will be able to start implementing the changes made in our code, hence releasing Debian 11 Support officially.

However, feel free to use the current stable version on your debian 11, as it has a lot of common check that will be present in the debian 11 CIS Benchmark anyways.
