### ISSUE TITLE
5.2.15 script not looking for match defined in the CIS_Debian_Linux_10_Benchmark_v1.0.0.pdf

### ISSUE THREAD

**Issue by LoupaLoupa** [ovh/debian-cis#196]
The script is looking only for diffie-hellman-group-exchange-sha256 but the documentation specifies that a much higher number of  Key Exchange algorithms can be use.

The documents specifies curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256 as possible strong algorithms.

Seems like the script should be change, but I am not sure of which one is right.( My first hardening)

Thanks for any help provided.

**Comment by ThibaultDewailly** [comment]
Hello !

Thanks for the report !
If you look closely, you'll notice that the list you're providing exactly fits this line : 

https://github.com/ovh/debian-cis/blob/master/bin/hardening/5.2.15_ssh_cry_kex.sh#L81

The search you're mentioning is only for debian 7 and under, which are (very) old distribution, we shall clean this in the future.

**Comment by LoupaLoupa** [comment]
Ok, thanks for the answer. If I understand correctly(I am not a bash expert), the condition is inverted. 7 -le current Debian version will always be true.

**Comment by ThibaultDewailly** [comment]
You're absolutely right, thanks for pointing it out.

This has been merged into master.

Have a great day !
