### ISSUE TITLE
Password hashes in /etc/shadow not SHA512

### ISSUE THREAD

**Issue by ITNerdbox** [ovh/debian-cis#209]
The default password hashing algorithm in Debian 12 is yescrypt, which apparently is a better to withstand offline password cracking compared to SHA512.

Currently I get the following message:

`99.5.4.5.2_acc_shadow_sha [ KO ] User root has a password that is not SHA512 hashed.`

Obviously, this is technically correct. However, considering this is apparently a better hashing algorithm, would it be possible to include this in the checks?

I can also understand this may be something that needs to be reported to CIS itself perhaps, thus this discussion.

**Comment by ThibaultDewailly** [comment]
Hello, and thank you for pointing it out.
You are right, yescrypt must be included as a valid hashing password.

Adding this in todo
