### ISSUE TITLE
Deprecated check 99.5.2.8_ssh_sys_sandbox

### ISSUE THREAD

**Issue by agrimal** [ovh/debian-cis#212]
The check [99.5.2.8_ssh_sys_sandbox](../blob/master/bin/hardening/99.5.2.8_ssh_sys_sandbox.sh) verifies that the `UsePrivilegeSeparation` parameter is present in the OpenSSH server config.

However this parameter is deprecated since version 7.5 ([release-7.5](https://www.openssh.com/txt/release-7.5)), this repo only supports Debian 10/11/12, and OpenSSH version in Debian 10 is 7.9.

Maybe you can remove this check ?
Thanks

**Comment by ThibaultDewailly** [comment]
Hello !

You are absolutely right, thank you for pointing it out ! I'll take care of it in a PR
