### ISSUE TITLE
can follow the guide, can't read etc/default/cis-hardening: No such file or directory

### ISSUE THREAD

**Issue by Ondjultomte** [ovh/debian-cis#217]
can follow the guide w/o errors

Followed this
`$ git clone https://github.com/ovh/debian-cis.git && cd debian-cis
$ cp debian/default /etc/default/cis-hardening
$ sed -i "s#CIS_LIB_DIR=.*#CIS_LIB_DIR='$(pwd)'/lib#" etc/default/cis-hardening
$ sed -i "s#CIS_CHECKS_DIR=.*#CIS_CHECKS_DIR='$(pwd)'/bin/hardening#" etc/default/cis-hardening
$ sed -i "s#CIS_CONF_DIR=.*#CIS_CONF_DIR='$(pwd)'/etc#" etc/default/cis-hardening
$ sed -i "s#CIS_TMP_DIR=.*#CIS_TMP_DIR='$(pwd)'/tmp#" etc/default/cis-hardening
$ bin/hardening/1.1.1.1_disable_freevxfs.sh --audit-all
hardening                 [INFO] Treating /opt/cis-hardening/bin`

results in:

```
root@myhost:/debian-cis# sed -i "s#CIS_LIB_DIR=.*#CIS_LIB_DIR='$(pwd)'/lib#" etc/default/cis-hardening
sed: can't read etc/default/cis-hardening: No such file or directory
```

**Comment by mgray88** [comment]
I believe this is a typo. All the `sed` lines should modify `/etc/default/cis-hardening`. Note the forward slash prepended to the path
