### ISSUE TITLE
Seeking approval for relicensing of software

### ISSUE THREAD

**Issue by JeremiahSecrist** [ovh/debian-cis#218]
Hello,

I'm currently working on a project available [here](https://github.com/JeremiahSecrist/regula-nix). While searching for resources that could save time, I came across your project. My project aims to eventually merge with [this MIT-licensed repository](https://github.com/NixOS/nixpkgs), and I'd like to request your approval beforehand.

Specifically, I plan to use scripts found [here](https://github.com/ovh/debian-cis/tree/master/bin/hardening). I'll need to adapt these scripts for Nix-specific checks, but they could save a significant amount of time. Thank you in advance for considering this request. Please feel free to ask if you have any further questions.

Best regards,
Jeremiah S

**Comment by ThibaultDewailly** [comment]
Hello @JeremiahSecrist,

You sure can use the scripts, the license authorize it.
Have a great day, and merry christmas.
