### ISSUE TITLE
hardening.sh --set-hardening-level does not work

### ISSUE THREAD

**Issue by highwayfixerman** [ovh/debian-cis#230]
Debian 12, up to date.

When I try to run:

./bin/hardening.sh --set-hardening-level 1

It simply gives me the help info, as if I have entered the command in incorrectly. Other switches work, such as --audit-all-enable-passed, --audit, --apply

I have even spun up a new VM from scratch, and still get this issue. I am unable to run the  --set-hardening-level switch.

**Comment by ThibaultDewailly** [comment]
Nice catch, Thank you
