### ISSUE TITLE
What CIS Benchmark is used exactly ? What do I implement ?

### ISSUE THREAD

**Issue by ManuGithubSteam** [ovh/debian-cis#235]
Hi OVH,

Thank you soo much for this repo and your work! We need to harden down Debian an as there are no STIGs this repo is one of my main resources. We prefer CIS anyway. Also openscap has not many profiles to work with.

But this begs the question: What is actually implemented ? Which CIS Benchmark ?

Sorry for my confusion but on the main Page it says it would implement PCI-DSS, but here https://github.com/ovh/debian-cis/issues/201 is says it implements the CIS_Debian_Linux_11_Benchmark, or now for Debian 12 i guess.

Or is the CIS_Debian_Linux_12_Benchmark PCI-DSS compliant ?

So which one is used ? I need this for documentation purposes to make it clear what security baseline gets implemented.

How does the hardeing level affect the outcome? So to say that hardening level 3 is PCI-DSS but level 2 is not compliant with it and so on.. 

Sorry for my confusion.

Thanks and have a great week!

**Comment by ThibaultDewailly** [comment]
Hello, and sorry for the late answer. 
 
"Sorry for my confusion but on the main Page it says it would implement PCI-DSS, "
This repository does not implement PCIDSS, but helps you meet PCIDSS OS hardening (Debian) requirement via technical audit and remediation.
It's currently based on 
CIS_Debian_Linux_10_Benchmark
CIS_Debian_Linux_11_Benchmark

CIS_Debian_Linux_12_Benchmark is in beta and will be released soon
