### ISSUE TITLE
Possible to use for Proxmox-Hosts?

### ISSUE THREAD

**Issue by JSuenram** [ovh/debian-cis#240]
Hi,
anyone tested this on a current Proxmox-Server?

**Comment by SleepTheGod** [comment]
Yes it works if you use debian via an iso on proxmox

**Comment by SleepTheGod** [comment]
> > Yes it works if you use debian via an iso on proxmox
> 
> And what about the native ProxmoxVE install ISO? It is based on Debian but with an Ubuntu-Kernel as fare as I know.

If you want you can check out my https://github.com/SleepTheGod/Firewall repo

**Comment by SleepTheGod** [comment]
> > > Yes it works if you use debian via an iso on proxmox
> > 
> > 
> > And what about the native ProxmoxVE install ISO? It is based on Debian but with an Ubuntu-Kernel as fare as I know.
> 
> If you want you can check out my https://github.com/SleepTheGod/Firewall repo

but no idea I don't really use ubuntu but if you are using proxmox you should be able to load up a debain iso
