### ISSUE TITLE
1.1.21_sticky_bit_world_writable_folder: Check failed

### ISSUE THREAD

**Issue by mohaa7** [ovh/debian-cis#248]
Running the following script leads to the error "Check failed with unexpected exit code: 1".
Script: [1.1.21_sticky_bit_world_writable_folder.sh](https://github.com/ovh/debian-cis/blob/master/bin/hardening/1.1.21_sticky_bit_world_writable_folder.sh)

If I run the following command, kinda inspired by the find snippet in the script:

```bash
root@Debian:~# find /dev /run / /dev/shm /run/lock /boot /run/user/1000 /media -xdev -ignore_readdir_race -type d \( -perm -0002 -a ! -perm -1000 \) -print`
```
then I get the following error:
```
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
```
Here is a related investigation: https://forums.debian.net/viewtopic.php?p=806684&sid=8661b51a8c76f9c3e9d4db6f841684cc#p806684

If I try to look at the directory "/run/user/1000/", then:
```
root@Debian:~# ls -lA /run/user/1000/ 1>/dev/null
ls: cannot access '/run/user/1000/doc': Permission denied
ls: cannot access '/run/user/1000/gvfs': Permission denied

VS

root@Debian:~# su --login "$(id -un 1000)" --command="ls -lA /run/user/1000/ 1>/dev/null"
(no error, indeed no output)
```

`# mount | grep fuse`:
```
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
I added the `! -path "/run/user/1000/doc" ! -path "/run/user/1000/gvfs"`to all `find` commands in the scrip, before `2>/dev/null`:
```
e.g: RESULT=$($SUDO_CMD find $FS_NAMES -xdev -ignore_readdir_race -type d \( -perm -0002 -a ! -perm -1000 \) ! -path "/run/user/1000/doc" ! -path "/run/user/1000/gvfs" -print 2>/dev/null)
```
But I still get that error:
```
# ./1.1.21_sticky_bit_world_writable_folder.sh --audit
.1.21_sticky_bit_world_w [INFO] Working on 1.1.21_sticky_bit_world_writable_folder
1.1.21_sticky_bit_world_w [INFO] [DESCRIPTION] Set sticky bit on world writable directories to prevent users from deleting or renaming files that are not owned by them.
1.1.21_sticky_bit_world_w [INFO] Checking Configuration
1.1.21_sticky_bit_world_w [INFO] Performing audit
1.1.21_sticky_bit_world_w [INFO] Checking if setuid is set on world writable Directories
1.1.21_sticky_bit_world_w [ KO ] Check failed with unexpected exit code: 1
```
Note: My OS is a new installed Debian 12 (+Gnome Desktop); Just updated. Only git, vim and curl are installed additionally.

**Comment by ThibaultDewailly** [comment]
Hello,

What you're seeing is normal, as fuse is designed to work this way (deny all other users, including root).
https://docs.kernel.org/filesystems/fuse.html

You might want to configure your fuse FS to allow root, or exclude the FS from the checks
