### ISSUE TITLE
Code has to be in `/opt/cis-hardening`

### ISSUE THREAD

**Issue by jedisct1** [ovh/debian-cis#3]
Looks like the scripts have to be present in `/opt/cis-hardening`.

Following the quick start guide doesn't work: `./bin/hardening.sh` immediately complains about `/opt/cis-hardening` not being present.

Could the `README` file be updated, or the code adjusted to run from arbitrary locations?

**Comment by ThibaultDewailly** [comment]
Root directory is defined in the default file, I have added a sed in the kick start as well as a folder check when running script so proper error can be thown.

currently in tests, should be prodded soon

**Comment by ThibaultDewailly** [comment]
Fixed merged in master
