### ISSUE TITLE
Variable error

### ISSUE THREAD

**Issue by Lejooohn** [ovh/debian-cis#46]
Hi,

On fresh install of Debian 10 i'm trying to use the script but when i follow the quickstart guide : 

~/debian-cis # bin/hardening/1.1.1.1_disable_freevxfs.sh --audit-all
1.1.1.1_disable_freevxfs  [INFO] Working on 1.1.1.1_disable_freevxfs
1.1.1.1_disable_freevxfs  [INFO] [DESCRIPTION] Disable mounting of freevxfs filesystems.
1.1.1.1_disable_freevxfs  [INFO] Checking Configuration
1.1.1.1_disable_freevxfs  [INFO] Performing audit
/root/debian-cis/lib/utils.sh: ligne 362: FILTER : variable sans liaison

Do you know why?

Regards

**Comment by jeremydenoun** [comment]
my bad, variable not renamed in previous PR (new PR fix that)

**Comment by Lejooohn** [comment]
Thanks @jeremydenoun
