### ISSUE TITLE
5.1.8_cron_users perms

### ISSUE THREAD

**Issue by jeremydenoun** [ovh/debian-cis#52]
check wait `/etc/cron.allow` `/etc/at.allow` perms `0644`,  correspond to CIS requirement (not writable) but this isn't a best practice `https://www.stigviewer.com/stig/oracle_linux_5/2016-06-01/finding/V-975` this should implement exact CIS test (not writable) or allow (400, 600, 640, 644)

**Comment by thibaultserti** [comment]
Will allow multiple permissions as you said.
