### ISSUE TITLE
5.2.15_ssh_cry_kex.sh kex validation method

### ISSUE THREAD

**Issue by jeremydenoun** [ovh/debian-cis#53]
The actual implementation method check specific `Key Exchange Algorithms` but this doesn't correspond to CIS requirement.

We should follow specs and check :
```
Run the following command and verify that output does not contain any of the listed weak Key Exchange algorithms
# sshd -T | grep kexalgorithms
```
detect (audit) / remove (apply) Weak Key Exchange Algorithms like :
```
 diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 diffie-hellman-group-exchange-sha1
```
(maybe *-sha1)

In my case I don't allow `diffie-hellman-group-exchange-sha256` so it's a false positive.

**Comment by jeremydenoun** [comment]
this can apply to 5.2.13, 5.2.14 too

**Comment by thibaultserti** [comment]
Ok I see we only check that strong algorithms are enabled but never that weak algos are disabled.

**Comment by thibaultserti** [comment]
I have only replace the macs and kex with the recommended one in CIS.
The fact is that it' checks that the content of the entire Kex line is *exactly* the one we put in the check. So I don't really think that it is necessary to check that no weak cipher is present.
