### ISSUE TITLE
Hardening Clarification Scripts Execution

### ISSUE THREAD

**Issue by guillermocol** [ovh/debian-cis#62]
Hello,

I have been going through the code and I would like to confirm the following steps:

**- If these scripts just do the hardening part, but don't test the server before is hardened?**
**- How I can run manually script by script? This is what I found in the "readme" file:**

### Configuration
Hardening scripts are in ``bin/hardening``. Each script has a corresponding
configuration file in ``etc/conf.d/[script_name].cfg``.
Each hardening script can be individually enabled from its configuration file.
For example, this is the default configuration file for ``disable_system_accounts``:

**- Is there a way to see which tests have passed and which test have not before doing the hardening?**

Thank you for your help.

**Comment by thibaultserti** [comment]
Hello, and thanks for your interest !

You can manually run a script by launching the `hardening.sh` script followed by the names of the scripts you want to run.

For example
```console
$ /opt/cis-hardening/bin/hardening.sh --audit 1.1.1.1_disable_freevxfs.sh 2.3.1_disable_nis.sh
```
To answer your second question, you can manually read the generated logs and check which check pass or didn't pass (it's really easy to see it with colors).
You can also use the option `--audit-all-enable-passed` to automatically enable for apply all checks that get a OK value on audit.
(See `MANUAL.md` for more precision)

**Comment by guillermocol** [comment]
Hi Thibaultserti, thank you for your clarifications, it was helpful.

I have been following these steps from the user guide:

$ git clone https://github.com/ovh/debian-cis.git && cd debian-cis
$ cp debian/default /etc/default/cis-hardening
$ sed -i "s#CIS_ROOT_DIR=.*#CIS_ROOT_DIR='$(pwd)'#" /etc/default/cis-hardening
$ bin/hardening/1.1.1.1_disable_freevxfs.sh --audit-all

But I get the following result:

_/home/admin/debian-cis-2021/bin/hardening# ./1.1.1.1_disable_freevxfs.sh --audit-all
Cannot find main.sh, have you correctly defined your root directory? Current value is /home/admin/debian-cis-2021/debian in /etc/default/cis-hardening_

- Will I need to create a config file in /etc/hardening for each test  needed?

- Also I tried to run it this way and I get:

./hardening.sh --audit-all --allow-unsupported-distribution
Your distribution has been identified as  which is not debian
find: '/home/admin/debian-cis-2021/debian/bin/hardening/': No such file or directory
################### SUMMARY ###################
      Total Available Checks : 0
         Total Runned Checks : 0
         Total Passed Checks : [     0/0 ]
         Total Failed Checks : [     0/0 ]
./hardening.sh: line 365: div: command not found
./hardening.sh: line 366: div: command not found
   Enabled Checks Percentage :  %
       Conformity Percentage : N.A %

The server is Debian 10 buxter: lsb_release -a

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Thank you for your help,

**Comment by guillermocol** [comment]
* One more note: Also about those config files in etc not sure of the format needed. Could it be just one line when is indicated as enabled or disabled?
Thank you again!

**Comment by guillermocol** [comment]
Hi Thibaultserti, I was testing this morning the config file, not sure what could be the issue :/ I tried to add the correct route in /etc/default/cis-hardening config file:

_CIS_ROOT_DIR='/home/admin/debian-cis-2021/bin/hardening/'_

This route is where all the hardening scripts are but still when I run this command: 
_./1.1.1.1_disable_freevxfs.sh --audit-all_

I get this:

_Cannot find main.sh, have you correctly defined your root directory? Current value is /home/admin/debian-cis-2021/bin/hardening/ in /etc/default/cis-hardening_

**Comment by thibaultserti** [comment]
> Hi Thibaultserti, thank you for your clarifications, it was helpful.
> 
> I have been following these steps from the user guide:
> 
> $ git clone https://github.com/ovh/debian-cis.git && cd debian-cis
> $ cp debian/default /etc/default/cis-hardening
> $ sed -i "s#CIS_ROOT_DIR=.*#CIS_ROOT_DIR='$(pwd)'#" /etc/default/cis-hardening
> $ bin/hardening/1.1.1.1_disable_freevxfs.sh --audit-all
> 
> But I get the following result:
> 
> _/home/admin/debian-cis-2021/bin/hardening# ./1.1.1.1_disable_freevxfs.sh --audit-all Cannot find main.sh, have you correctly defined your root directory? Current value is /home/admin/debian-cis-2021/debian in /etc/default/cis-hardening_

I don't understand why you have `home/admin/debian-cis-2021/debian` as the root directory. You should have only `/home/admin/debian-cis` if you cloned the repo in `/home/admin` and executed the line you copied above/ You must have executed something else.

>     * Will I need to create a config file in /etc/hardening for each test  needed?

Conf files are created with default values **not in /etc/hardening** but in **debian-cis/etc/conf.d/**

>     * Also I tried to run it this way and I get:
> 
> 
> ./hardening.sh --audit-all --allow-unsupported-distribution
> Your distribution has been identified as which is not debian
> find: '/home/admin/debian-cis-2021/debian/bin/hardening/': No such file or directory
> ################### SUMMARY ###################
> Total Available Checks : 0
> Total Runned Checks : 0
> Total Passed Checks : [ 0/0 ]
> Total Failed Checks : [ 0/0 ]
> ./hardening.sh: line 365: div: command not found
> ./hardening.sh: line 366: div: command not found
> Enabled Checks Percentage : %
> Conformity Percentage : N.A %
> 
> The server is Debian 10 buxter: lsb_release -a
> 
> Distributor ID: Debian
> Description: Debian GNU/Linux 10 (buster)
> Release: 10
> Codename: buster

This is because `main.sh` is not found and not executed, so nothing works.

**Comment by thibaultserti** [comment]
> Hi Thibaultserti, I was testing this morning the config file, not sure what could be the issue :/ I tried to add the correct route in /etc/default/cis-hardening config file:
> 
> _CIS_ROOT_DIR='/home/admin/debian-cis-2021/bin/hardening/'_
> 
> This route is where all the hardening scripts are but still when I run this command:
> _./1.1.1.1_disable_freevxfs.sh --audit-all_
> 
> I get this:
> 
> _Cannot find main.sh, have you correctly defined your root directory? Current value is /home/admin/debian-cis-2021/bin/hardening/ in /etc/default/cis-hardening_

The root directory is only `/home/admin/debian-cis-2021`

**Comment by thibaultserti** [comment]
Consider using the .deb package provided in the release.

**Comment by guillermocol** [comment]
Hi Thibaultserti,

The change of the root directory helped to be able to run the scripts. I will continue testing and see if I have any other questions. 
Thank you very much
Guillermo
