### ISSUE TITLE
CIS Hardening Question

### ISSUE THREAD

**Issue by guillermocol** [ovh/debian-cis#64]
Hello,

I have been running the scripts and I was able to get some results, but trying to do some remediation, I was not able to run correctly what is needed. This is an example that I have run:

**In debian-cis-2021/bin/hardening route:**

./1.4.1_install_tripwire.sh --apply
1.4.1_install_tripwire    [INFO] Working on 1.4.1_install_tripwire
1.4.1_install_tripwire    [INFO] [DESCRIPTION] Ensure tripwire package is installed.
1.4.1_install_tripwire    [INFO] Checking Configuration
1.4.1_install_tripwire    [INFO] Performing audit
1.4.1_install_tripwire    [ KO ] tripwire is not installed!
1.4.1_install_tripwire    [ KO ] Check Failed

Not sure how to use it to remediate this vulnerability.

- Also I would like to know the difference between /bin/hardening tests and /tests/hardening tests folder

Thank you for your help

**Comment by Lejooohn** [comment]
Hi,

Did you ensure that the cfg file associate to this script is correctly enabled before you use the --apply?

For you example, you have to check if "status=enabled" in debian-cis-2021/etc/conf.d/1.4.1_install_tripwire.cfg : 

```
~/debian-cis/etc/conf.d # cat 1.4.1_install_tripwire.cfg
# Configuration for 1.4.1_install_tripwire
status=enabled
```

For you second question, i don't understand what you mean ^^

Regards

**Comment by guillermocol** [comment]
Thank you for your answer it worked smoothly :)

- There are two folders the /debian-cis/bin/hardening/  and /debian-cis/tests/hardening  I don't know the difference between these 2, I think the second one is used for the docker container creation purpose, but I am not sure as the files have different sizes comparing these 2 folders.

- Also hardening, some of the scripts give me this result: 

 ./1.1.1.1_disable_freevxfs.sh --apply
1.1.1.1_disable_freevxfs  [INFO] Working on 1.1.1.1_disable_freevxfs
1.1.1.1_disable_freevxfs  [INFO] [DESCRIPTION] Disable mounting of freevxfs filesystems.
1.1.1.1_disable_freevxfs  [INFO] Checking Configuration
1.1.1.1_disable_freevxfs  [INFO] Performing audit
/home/admin/debian-cis-2021/lib/utils.sh: line 362: FILTER: unbound variable

Seems like informational not marking it as KO or OK, not sure what it means. The message in this case seems the same doing --audit or --apply

Thank you,
guillermo

**Comment by thibaultserti** [comment]
The folder `tests/hardening` is just the batch of functional test we're running to check if have not broken anything.

>  /home/admin/debian-cis-2021/lib/utils.sh: line 362: FILTER: unbound variable

this comes from a broken master fixed in https://github.com/ovh/debian-cis/commit/896d277d953d622231903e14660d203dc76b436a

I you want more stable version keep on using released version (and .deb package)
