### ISSUE TITLE
docker issue during remediation

### ISSUE THREAD

**Issue by guillermocol** [ovh/debian-cis#71]
Hello,

I was running part of the remediation tests and we found out that is modifying the docker container files permissions. How could we change this? We don't want that docker would be affected.
The partition is /var/lib/docker, but how we could avoid to modify those directories. Also not sure which remediation file caused this.
Basically changes the permissions of some files from "specific service user" to "root". 

Thank you,

**Comment by thibaultserti** [comment]
I'm not sure which check could have change the permissions of `/var/lib/` ... For me there is none. I suggest you to try to find the checks that modify the permission and to disable it.
