### ISSUE TITLE
Info Messages in the report

### ISSUE THREAD

**Issue by guillermocol** [ovh/debian-cis#76]
Hello,

 I was running the audit tests and the hardening and I would like to know what is the meaning of those tests marked as INFO instead of OK or KO.

6.2.13_set_perm_on_user_n [ OK ] Check Passed
hardening                 [INFO] Treating /home/deployment/config/cis-benchmark/cis-debian10/bin/hardening/6.2.14_find_user_rhosts_files.sh
6.2.14_find_user_rhosts_f [INFO] Working on 6.2.14_find_user_rhosts_files
6.2.14_find_user_rhosts_f [INFO] [DESCRIPTION] No user's .rhosts file.
6.2.14_find_user_rhosts_f [INFO] Checking Configuration
6.2.14_find_user_rhosts_f [INFO] Performing audit
6.2.14_find_user_rhosts_f [ OK ] No .rhosts present in users home directory
6.2.14_find_user_rhosts_f [ OK ] Check Passed

In the remediation, all of those the config file is marked as "enabled" to harden those tests. I think I don't understand those marked as INFO after hardening. What does this mean? does it mean those tests failed too? 

Thanks,
Best regards

**Comment by thibaultserti** [comment]
The [ INFO ] lines refer to the same check as the [ OK ] here (6.2.14). It's just to give a description of the check wich is running.
Here it says that it checks there is "No user's .rhosts file"
Furthermore it describes every step (checking conf, audit/apply)
