### ISSUE TITLE
Addition of auditd rules in not persistent

### ISSUE THREAD

**Issue by ycooper** [ovh/debian-cis#83]
Rules for auditd in section 4.1 are being added directly to
`/etc/audit/audit.rules`
which means they don't get applied and they get flushed at restart of auditd service. The right location for them is at
`/etc/audit/rules.d/`

**Comment by thibaultserti** [comment]
It does'nt seem to be a problem according to the documentation. (https://manpages.debian.org/buster/auditd/auditd.8.en.html)
However, I found that it is an issue with Redhat. (https://access.redhat.com/solutions/1505033)
