### ISSUE TITLE
99.5.2.8_ssh_sys_sandbox - UsePrivilegeSeparation

### ISSUE THREAD

**Issue by y-martin** [ovh/debian-cis#89]
Hello

This option is deprecated in openssh-7.5.

Changelog available here:
https://www.openssh.com/txt/release-7.5

Regards

**Comment by thibaultserti** [comment]
Every 99.x are either OVH bonuc checks or Legacy CIS Hardening.
This one is legacy from Debian 8, so it's not a surprise that it's deprecated.
Disable it if not needed.
